export const jobs = [
  {
    id: 'job123',
    title: 'Software Engineer',
    company: 'ABC Company',
    location: 'New York, NY',
    description:
      'We are seeking a skilled Software Engineer to join our team...',
    requirements: "Bachelor's degree in Computer Science or related field...",
    salary: 'Competitive',
    createdAt: '2023-06-05T10:00:00Z',
    updatedAt: '2023-06-05T14:30:00Z',
  },
  {
    id: 'job456',
    title: 'Web Developer',
    company: 'XYZ Corporation',
    location: 'San Francisco, CA',
    description:
      'Join our dynamic team as a Web Developer and contribute to...',
    requirements: 'Proficiency in HTML, CSS, and JavaScript...',
    salary: 'Negotiable',
    createdAt: '2023-06-05T11:15:00Z',
    updatedAt: '2023-06-05T16:45:00Z',
  },
  {
    id: 'job789',
    title: 'Data Scientist',
    company: '123 Industries',
    location: 'Chicago, IL',
    description:
      'We are looking for a talented Data Scientist to join our team...',
    requirements: "Master's or Ph.D. in a quantitative field...",
    salary: 'Competitive',
    createdAt: '2023-06-05T09:30:00Z',
    updatedAt: '2023-06-05T13:45:00Z',
  },
  {
    id: 'job987',
    title: 'UX Designer',
    company: 'Design Co.',
    location: 'Seattle, WA',
    description: 'Seeking a creative UX Designer to shape user experiences...',
    requirements: 'Strong portfolio showcasing UX design skills...',
    salary: 'Commensurate with experience',
    createdAt: '2023-06-05T14:00:00Z',
    updatedAt: '2023-06-05T18:30:00Z',
  },
  {
    id: 'job654',
    title: 'Marketing Manager',
    company: 'Global Marketing Solutions',
    location: 'London, UK',
    description:
      'We are hiring a Marketing Manager to oversee our marketing...',
    requirements: "Bachelor's degree in Marketing or related field...",
    salary: 'Competitive',
    createdAt: '2023-06-05T10:45:00Z',
    updatedAt: '2023-06-05T15:15:00Z',
  },
  {
    id: 'job321',
    title: 'Sales Representative',
    company: 'Salesforce Inc.',
    location: 'Los Angeles, CA',
    description:
      'Join our sales team as a Sales Representative and drive revenue...',
    requirements: 'Proven track record in sales and negotiation skills...',
    salary: 'Base salary + commission',
    createdAt: '2023-06-05T13:30:00Z',
    updatedAt: '2023-06-05T17:45:00Z',
  },
  {
    id: 'job654',
    title: 'Frontend Developer',
    company: 'Tech Solutions Ltd.',
    location: 'Berlin, Germany',
    description: 'We are seeking a talented Frontend Developer to build...',
    requirements: 'Strong proficiency in JavaScript, HTML, and CSS...',
    salary: 'Negotiable',
    createdAt: '2023-06-05T12:15:00Z',
    updatedAt: '2023-06-05T16:30:00Z',
  },
  {
    id: 'job987',
    title: 'Product Manager',
    company: 'Innovate Tech',
    location: 'San Diego, CA',
    description: 'We are hiring a Product Manager to drive the development...',
    requirements: "Bachelor's degree in Business, Computer Science...",
    salary: 'Competitive',
    createdAt: '2023-06-05T09:45:00Z',
    updatedAt: '2023-06-05T14:00:00Z',
  },
  {
    id: 'job123',
    title: 'Graphic Designer',
    company: 'Creative Agency',
    location: 'Paris, France',
    description: 'Join our design team as a Graphic Designer and create...',
    requirements: 'Proficiency in Adobe Creative Suite...',
    salary: 'Commensurate with experience',
    createdAt: '2023-06-05T15:30:00Z',
    updatedAt: '2023-06-05T19:45:00Z',
  },
  {
    id: 'job456',
    title: 'Data Analyst',
    company: 'Analytics Inc.',
    location: 'Toronto, Canada',
    description: 'Seeking a skilled Data Analyst to analyze and interpret...',
    requirements: "Bachelor's degree in Statistics, Mathematics...",
    salary: 'Competitive',
    createdAt: '2023-06-05T11:30:00Z',
    updatedAt: '2023-06-05T16:00:00Z',
  },
  {
    id: 'job789',
    title: 'UI Designer',
    company: 'Digital Solutions',
    location: 'Sydney, Australia',
    description:
      'We are looking for a creative UI Designer to join our team...',
    requirements: 'Proven experience in UI design and prototyping tools...',
    salary: 'Negotiable',
    createdAt: '2023-06-05T14:45:00Z',
    updatedAt: '2023-06-05T19:00:00Z',
  },
  {
    id: 'job987',
    title: 'Full Stack Developer',
    company: 'Tech Innovators',
    location: 'Austin, TX',
    description: 'Join our development team as a Full Stack Developer...',
    requirements: 'Proficiency in front-end and back-end technologies...',
    salary: 'Competitive',
    createdAt: '2023-06-05T13:00:00Z',
    updatedAt: '2023-06-05T17:15:00Z',
  },
  {
    id: 'job113',
    title: 'Project Manager',
    company: 'Global Solutions',
    location: 'Singapore',
    description: 'We are hiring a Project Manager to oversee and...',
    requirements: 'Strong organizational and leadership skills...',
    salary: 'Competitive',
    createdAt: '2023-06-05T12:45:00Z',
    updatedAt: '2023-06-05T17:00:00Z',
  },
]
