import Footer from '@/components/Layout/Footer'
import Navbar from '@/components/Layout/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Jobs Board',
  description: 'Generated by M.Raza',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <>
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </>
    </html>
  )
}
