export const jobs = [
  {
    jobId:'job111',
    jobTitle: 'Software Engineer',
    contactName: 'John Smith',
    contactEmail: 'john@example.com',
    contactPhone: '123-456-7890',
    companyName: 'ABC Company',
    industry: 'Technology',
    location: 'New York, NY',
    jobDescription:
      'We are seeking a skilled Software Engineer to join our team...',
    employmentType: 'Full-time',
    skillsQualifications:
      "Bachelor's degree in Computer Science or related field...",
    compensationBenefits: 'Competitive salary and benefits package',
    applicationProcess:
      'Please email your resume and cover letter to the contact email provided.',
    applicationDeadline: '2023-07-15',
  },
  {
    jobId:'job112',
    jobTitle: 'Web Developer',
    contactName: 'Jane Doe',
    contactEmail: 'jane@example.com',
    contactPhone: '987-654-3210',
    companyName: 'XYZ Corporation',
    industry: 'Technology',
    location: 'San Francisco, CA',
    jobDescription:
      'Join our dynamic team as a Web Developer and contribute to...',
    employmentType: 'Contract',
    skillsQualifications: 'Proficiency in HTML, CSS, and JavaScript...',
    compensationBenefits: 'Negotiable based on experience',
    applicationProcess:
      'To apply, please visit our website and complete the online application form.',
    applicationDeadline: '2023-07-31',
  },
  {
    jobId:'job113',
    jobTitle: 'Data Scientist',
    contactName: 'Sarah Johnson',
    contactEmail: 'sarah@example.com',
    contactPhone: '456-789-0123',
    companyName: '123 Industries',
    industry: 'Technology',
    location: 'Chicago, IL',
    jobDescription:
      'We are looking for a talented Data Scientist to join our team...',
    employmentType: 'Full-time',
    skillsQualifications: "Master's or Ph.D. in a quantitative field...",
    compensationBenefits: 'Competitive salary and benefits package',
    applicationProcess:
      'To apply, please submit your resume and academic transcripts to the contact email provided.',
    applicationDeadline: '2023-07-31',
  },
  {
    jobId:'job114',
    jobTitle: 'UX Designer',
    contactName: 'Alex Williams',
    contactEmail: 'alex@example.com',
    contactPhone: '234-567-8901',
    companyName: 'Design Co.',
    industry: 'Design',
    location: 'Seattle, WA',
    jobDescription:
      'Seeking a creative UX Designer to shape user experiences...',
    employmentType: 'Full-time',
    skillsQualifications: 'Strong portfolio showcasing UX design skills...',
    compensationBenefits: 'Commensurate with experience',
    applicationProcess:
      'Please send your portfolio and resume to the contact email provided.',
    applicationDeadline: '2023-07-15',
  },
  {
    jobId:'job115',
    jobTitle: 'Marketing Manager',
    contactName: 'Michael Thompson',
    contactEmail: 'michael@example.com',
    contactPhone: '789-012-3456',
    companyName: 'Global Marketing Solutions',
    industry: 'Marketing',
    location: 'London, UK',
    jobDescription:
      'We are hiring a Marketing Manager to oversee our marketing...',
    employmentType: 'Full-time',
    skillsQualifications: "Bachelor's degree in Marketing or related field...",
    compensationBenefits: 'Competitive salary and benefits package',
    applicationProcess:
      'To apply, please submit your resume and cover letter to the contact email provided.',
    applicationDeadline: '2023-07-31',
  },
  {
    jobId:'job116',
    jobTitle: 'Sales Representative',
    contactName: 'Emily Wilson',
    contactEmail: 'emily@example.com',
    contactPhone: '012-345-6789',
    companyName: 'Salesforce Inc.',
    industry: 'Sales',
    location: 'Los Angeles, CA',
    jobDescription:
      'Join our sales team as a Sales Representative and drive revenue...',
    employmentType: 'Full-time',
    skillsQualifications:
      'Proven track record in sales and negotiation skills...',
    compensationBenefits: 'Base salary + commission',
    applicationProcess:
      'To apply, please submit your resume and a brief description of your sales experience to the contact email provided.',
    applicationDeadline: '2023-07-15',
  },
  {
    jobId:'job117',
    jobTitle: 'Frontend Developer',
    contactName: 'David Brown',
    contactEmail: 'david@example.com',
    contactPhone: '345-678-9012',
    companyName: 'Tech Solutions Ltd.',
    industry: 'Technology',
    location: 'Berlin, Germany',
    jobDescription: 'We are seeking a talented Frontend Developer to build...',
    employmentType: 'Full-time',
    skillsQualifications: 'Strong proficiency in JavaScript, HTML, and CSS...',
    compensationBenefits: 'Negotiable based on experience',
    applicationProcess:
      'To apply, please submit your resume and portfolio to the contact email provided.',
    applicationDeadline: '2023-07-31',
  },
  {
    jobId:'job118',
    jobTitle: 'Product Manager',
    contactName: 'Jessica Davis',
    contactEmail: 'jessica@example.com',
    contactPhone: '567-890-1234',
    companyName: 'Innovate Tech',
    industry: 'Technology',
    location: 'San Diego, CA',
    jobDescription:
      'We are hiring a Product Manager to drive the development...',
    employmentType: 'Full-time',
    skillsQualifications: "Bachelor's degree in Business, Computer Science...",
    compensationBenefits: 'Competitive salary and benefits package',
    applicationProcess:
      'To apply, please submit your resume and cover letter to the contact email provided.',
    applicationDeadline: '2023-07-15',
  },
  {
    jobId:'job119',
    jobTitle: 'Graphic Designer',
    contactName: 'Olivia Wilson',
    contactEmail: 'olivia@example.com',
    contactPhone: '890-123-4567',
    companyName: 'Creative Agency',
    industry: 'Design',
    location: 'Paris, France',
    jobDescription: 'Join our design team as a Graphic Designer and create...',
    employmentType: 'Full-time',
    skillsQualifications: 'Proficiency in Adobe Creative Suite...',
    compensationBenefits: 'Commensurate with experience',
    applicationProcess:
      'To apply, please submit your portfolio and resume to the contact email provided.',
    applicationDeadline: '2023-07-31',
  },
  {
    jobId:'job120',
    jobTitle: 'Data Analyst',
    contactName: 'Daniel Johnson',
    contactEmail: 'daniel@example.com',
    contactPhone: '678-901-2345',
    companyName: 'Analytics Inc.',
    industry: 'Technology',
    location: 'Toronto, Canada',
    jobDescription:
      'Seeking a skilled Data Analyst to analyze and interpret...',
    employmentType: 'Full-time',
    skillsQualifications: "Bachelor's degree in Statistics, Mathematics...",
    compensationBenefits: 'Competitive salary and benefits package',
    applicationProcess:
      'To apply, please submit your resume and academic transcripts to the contact email provided.',
    applicationDeadline: '2023-07-15',
  },
  {
    jobId:'job121',
    jobTitle: 'UI Designer',
    contactName: 'Sophia Martinez',
    contactEmail: 'sophia@example.com',
    contactPhone: '901-234-5678',
    companyName: 'Digital Solutions',
    industry: 'Design',
    location: 'Sydney, Australia',
    jobDescription:
      'We are looking for a creative UI Designer to join our team...',
    employmentType: 'Full-time',
    skillsQualifications:
      'Proven experience in UI design and prototyping tools...',
    compensationBenefits: 'Negotiable based on experience',
    applicationProcess:
      'To apply, please submit your portfolio and resume to the contact email provided.',
    applicationDeadline: '2023-07-31',
  },
  {
    jobId:'job122',
    jobTitle: 'Full Stack Developer',
    contactName: 'Matthew Wilson',
    contactEmail: 'matthew@example.com',
    contactPhone: '123-456-7890',
    companyName: 'Tech Innovators',
    industry: 'Technology',
    location: 'Austin, TX',
    jobDescription: 'Join our development team as a Full Stack Developer...',
    employmentType: 'Full-time',
    skillsQualifications:
      'Proficiency in front-end and back-end technologies...',
    compensationBenefits: 'Competitive salary and benefits package',
    applicationProcess:
      'To apply, please submit your resume and portfolio to the contact email provided.',
    applicationDeadline: '2023-07-15',
  },
  {
    jobId:'job123',
    jobTitle: 'Project Manager',
    contactName: 'Christopher Davis',
    contactEmail: 'christopher@example.com',
    contactPhone: '234-567-8901',
    companyName: 'Global Solutions',
    industry: 'Management',
    location: 'Singapore',
    jobDescription: 'We are hiring a Project Manager to oversee and...',
    employmentType: 'Full-time',
    skillsQualifications: 'Strong organizational and leadership skills...',
    compensationBenefits: 'Competitive salary and benefits package',
    applicationProcess:
      'To apply, please submit your resume and cover letter to the contact email provided.',
    applicationDeadline: '2023-07-31',
  },
  {
    jobId:'job1124',
    jobTitle: 'Software Engineer',
    contactName: 'Emily Johnson',
    contactEmail: 'emily@example.com',
    contactPhone: '345-678-9012',
    companyName: 'Tech Solutions Ltd.',
    industry: 'Technology',
    location: 'Berlin, Germany',
    jobDescription:
      'We are seeking a skilled Software Engineer to join our team...',
    employmentType: 'Full-time',
    skillsQualifications:
      "Bachelor's degree in Computer Science or related field...",
    compensationBenefits: 'Competitive salary and benefits package',
    applicationProcess:
      'To apply, please submit your resume and cover letter to the contact email provided.',
    applicationDeadline: '2023-07-31',
  },
  {
    jobId:'job125',
    jobTitle: 'Web Developer',
    contactName: 'Michael Brown',
    contactEmail: 'michael@example.com',
    contactPhone: '456-789-0123',
    companyName: 'XYZ Corporation',
    industry: 'Technology',
    location: 'San Francisco, CA',
    jobDescription:
      'Join our dynamic team as a Web Developer and contribute to...',
    employmentType: 'Contract',
    skillsQualifications: 'Proficiency in HTML, CSS, and JavaScript...',
    compensationBenefits: 'Negotiable based on experience',
    applicationProcess:
      'To apply, please visit our website and complete the online application form.',
    applicationDeadline: '2023-07-15',
  },
  {
    jobId:'job126',
    jobTitle: 'Data Scientist',
    contactName: 'Oliver Wilson',
    contactEmail: 'oliver@example.com',
    contactPhone: '567-890-1234',
    companyName: '123 Industries',
    industry: 'Technology',
    location: 'San Francisco, CA',
    jobDescription:
      'Join our dynamic team as a Web Developer and contribute to...',
    employmentType: 'Contract',
    skillsQualifications: 'Proficiency in HTML, CSS, and JavaScript...',
    compensationBenefits: 'Negotiable based on experience',
    applicationProcess:
      'To apply, please visit our website and complete the online application form.',
    applicationDeadline: '2023-07-15',
  },
]

export const oldjob = [
  {
    id: 'job123',
    title: 'Software Engineer',
    company: 'ABC Company',
    location: 'New York, NY',
    description:
      'We are seeking a skilled Software Engineer to join our team...',
    requirements: "Bachelor's degree in Computer Science or related field...",
    salary: 'Competitive',
    createdAt: '2023-06-05T10:00:00Z',
    updatedAt: '2023-06-05T14:30:00Z',
  },
  {
    id: 'job456',
    title: 'Web Developer',
    company: 'XYZ Corporation',
    location: 'San Francisco, CA',
    description:
      'Join our dynamic team as a Web Developer and contribute to...',
    requirements: 'Proficiency in HTML, CSS, and JavaScript...',
    salary: 'Negotiable',
    createdAt: '2023-06-05T11:15:00Z',
    updatedAt: '2023-06-05T16:45:00Z',
  },
  {
    id: 'job789',
    title: 'Data Scientist',
    company: '123 Industries',
    location: 'Chicago, IL',
    description:
      'We are looking for a talented Data Scientist to join our team...',
    requirements: "Master's or Ph.D. in a quantitative field...",
    salary: 'Competitive',
    createdAt: '2023-06-05T09:30:00Z',
    updatedAt: '2023-06-05T13:45:00Z',
  },
  {
    id: 'job987',
    title: 'UX Designer',
    company: 'Design Co.',
    location: 'Seattle, WA',
    description: 'Seeking a creative UX Designer to shape user experiences...',
    requirements: 'Strong portfolio showcasing UX design skills...',
    salary: 'Commensurate with experience',
    createdAt: '2023-06-05T14:00:00Z',
    updatedAt: '2023-06-05T18:30:00Z',
  },
  {
    id: 'job654',
    title: 'Marketing Manager',
    company: 'Global Marketing Solutions',
    location: 'London, UK',
    description:
      'We are hiring a Marketing Manager to oversee our marketing...',
    requirements: "Bachelor's degree in Marketing or related field...",
    salary: 'Competitive',
    createdAt: '2023-06-05T10:45:00Z',
    updatedAt: '2023-06-05T15:15:00Z',
  },
  {
    id: 'job321',
    title: 'Sales Representative',
    company: 'Salesforce Inc.',
    location: 'Los Angeles, CA',
    description:
      'Join our sales team as a Sales Representative and drive revenue...',
    requirements: 'Proven track record in sales and negotiation skills...',
    salary: 'Base salary + commission',
    createdAt: '2023-06-05T13:30:00Z',
    updatedAt: '2023-06-05T17:45:00Z',
  },
  {
    id: 'job654',
    title: 'Frontend Developer',
    company: 'Tech Solutions Ltd.',
    location: 'Berlin, Germany',
    description: 'We are seeking a talented Frontend Developer to build...',
    requirements: 'Strong proficiency in JavaScript, HTML, and CSS...',
    salary: 'Negotiable',
    createdAt: '2023-06-05T12:15:00Z',
    updatedAt: '2023-06-05T16:30:00Z',
  },
  {
    id: 'job987',
    title: 'Product Manager',
    company: 'Innovate Tech',
    location: 'San Diego, CA',
    description: 'We are hiring a Product Manager to drive the development...',
    requirements: "Bachelor's degree in Business, Computer Science...",
    salary: 'Competitive',
    createdAt: '2023-06-05T09:45:00Z',
    updatedAt: '2023-06-05T14:00:00Z',
  },
  {
    id: 'job1231',
    title: 'Graphic Designer',
    company: 'Creative Agency',
    location: 'Paris, France',
    description: 'Join our design team as a Graphic Designer and create...',
    requirements: 'Proficiency in Adobe Creative Suite...',
    salary: 'Commensurate with experience',
    createdAt: '2023-06-05T15:30:00Z',
    updatedAt: '2023-06-05T19:45:00Z',
  },
  {
    id: 'job456',
    title: 'Data Analyst',
    company: 'Analytics Inc.',
    location: 'Toronto, Canada',
    description: 'Seeking a skilled Data Analyst to analyze and interpret...',
    requirements: "Bachelor's degree in Statistics, Mathematics...",
    salary: 'Competitive',
    createdAt: '2023-06-05T11:30:00Z',
    updatedAt: '2023-06-05T16:00:00Z',
  },
  {
    id: 'job789',
    title: 'UI Designer',
    company: 'Digital Solutions',
    location: 'Sydney, Australia',
    description:
      'We are looking for a creative UI Designer to join our team...',
    requirements: 'Proven experience in UI design and prototyping tools...',
    salary: 'Negotiable',
    createdAt: '2023-06-05T14:45:00Z',
    updatedAt: '2023-06-05T19:00:00Z',
  },
  {
    id: 'job987',
    title: 'Full Stack Developer',
    company: 'Tech Innovators',
    location: 'Austin, TX',
    description: 'Join our development team as a Full Stack Developer...',
    requirements: 'Proficiency in front-end and back-end technologies...',
    salary: 'Competitive',
    createdAt: '2023-06-05T13:00:00Z',
    updatedAt: '2023-06-05T17:15:00Z',
  },
  {
    id: 'job113',
    title: 'Project Manager',
    company: 'Global Solutions',
    location: 'Singapore',
    description: 'We are hiring a Project Manager to oversee and...',
    requirements: 'Strong organizational and leadership skills...',
    salary: 'Competitive',
    createdAt: '2023-06-05T12:45:00Z',
    updatedAt: '2023-06-05T17:00:00Z',
  },
]
